<template>
  <q-page class="q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-h6">Compras</div><div class="text-caption text-grey-7">Historial de ingreso de mercadería</div></div><q-space/><q-btn color="positive" icon="add_business" label="Nueva compra" no-caps to="/compras/nueva"/></div>
    <div class="row q-col-gutter-sm q-mb-sm"><div v-for="c in cards" :key="c.label" class="col-6 col-md-3"><q-card flat bordered><q-card-section class="q-pa-sm"><div class="text-caption text-grey-7">{{c.label}}</div><div class="text-h6 text-weight-bold">{{c.money?'Bs ':''}}{{c.money?money(c.value):c.value}}</div></q-card-section></q-card></div></div>
    <q-card flat bordered><q-card-section class="row q-col-gutter-sm q-pa-sm"><q-input v-model="search" outlined dense debounce="300" clearable label="Buscar compra, factura o proveedor" class="col-12 col-md-5" @update:model-value="load"/><q-input v-model="desde" outlined dense type="date" label="Desde" class="col-6 col-md-2" @update:model-value="load"/><q-input v-model="hasta" outlined dense type="date" label="Hasta" class="col-6 col-md-2" @update:model-value="load"/></q-card-section><q-table flat dense :rows="rows" :columns="columns" row-key="id" :loading="loading" v-model:pagination="pagination" @request="request"><template #body-cell-total="p"><q-td :props="p"><b>Bs {{money(p.value)}}</b></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge :color="p.value==='COMPLETADA'?'positive':'negative'">{{p.value}}</q-badge></q-td></template><template #body-cell-actions="p"><q-td :props="p"><q-btn-dropdown dense flat color="primary" icon="more_vert" dropdown-icon="none"><q-list dense style="min-width:165px"><q-item clickable v-close-popup @click="detail(p.row)"><q-item-section avatar><q-icon name="visibility" color="primary"/></q-item-section><q-item-section>Ver detalle</q-item-section></q-item><q-item clickable v-close-popup @click="printRow(p.row)"><q-item-section avatar><q-icon name="print" color="blue-grey"/></q-item-section><q-item-section>Imprimir</q-item-section></q-item><q-separator/><q-item v-if="p.row.estado==='COMPLETADA'" clickable v-close-popup class="text-negative" @click="cancel(p.row)"><q-item-section avatar><q-icon name="cancel"/></q-item-section><q-item-section>Anular compra</q-item-section></q-item></q-list></q-btn-dropdown></q-td></template></q-table></q-card>
    <q-dialog v-model="dialog"><q-card style="width:800px;max-width:96vw"><q-card-section class="row items-center"><div><div class="text-h6">{{selected.numero}}</div><div class="text-caption">{{selected.proveedor_nombre}} · {{date(selected.fecha)}}</div></div><q-space/><q-btn round flat color="primary" icon="print" @click="printPurchase(selected,company)"/><q-btn round flat icon="close" v-close-popup/></q-card-section><q-table flat dense :rows="selected.detalles||[]" :columns="detailColumns" row-key="id" hide-pagination :rows-per-page-options="[0]"/><q-card-section class="text-right text-h6">Total Bs {{money(selected.total)}}</q-card-section></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, getCurrentInstance, reactive, ref } from 'vue'
import { printPurchase } from '../../addons/compraPrint'
const {proxy}=getCurrentInstance(),rows=ref([]),loading=ref(false),search=ref(''),desde=ref(''),hasta=ref(''),dialog=ref(false),selected=reactive({}),summary=reactive({total:0,efectivo:0,qr:0,cantidad:0}),pagination=ref({page:1,rowsPerPage:20,rowsNumber:0})
const company=reactive({nombre_empresa:'Mundolac',nit:'',direccion:'',telefono:'',logo_url:''})
const money=v=>Number(v||0).toFixed(2),date=v=>v?new Date(v).toLocaleString('es-BO'):'',cards=computed(()=>[{label:'Total comprado',value:summary.total,money:true},{label:'Efectivo',value:summary.efectivo,money:true},{label:'QR',value:summary.qr,money:true},{label:'Compras',value:summary.cantidad}])
const columns=[{name:'actions',label:'',field:'actions'},{name:'numero',label:'Nº compra',field:'numero',align:'left'},{name:'fecha',label:'Fecha',field:r=>date(r.fecha),align:'left'},{name:'proveedor',label:'Proveedor',field:'proveedor_nombre',align:'left'},{name:'factura',label:'Factura',field:'numero_factura',align:'left'},{name:'pago',label:'Pago',field:'tipo_pago',align:'center'},{name:'total',label:'Total',field:'total',align:'right'},{name:'estado',label:'Estado',field:'estado',align:'center'}]
const detailColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Producto',field:'nombre',align:'left'},{name:'lote',label:'Lote',field:'lote'},{name:'fecha',label:'Vencimiento',field:'fecha_vencimiento'},{name:'cantidad',label:'Cantidad',field:'cantidad',align:'right'},{name:'precio',label:'Costo',field:r=>`Bs ${money(r.precio_unitario)}`,align:'right'},{name:'total',label:'Total',field:r=>`Bs ${money(r.total)}`,align:'right'}]
function params(){return {q:search.value,desde:desde.value,hasta:hasta.value}}function load(){request({pagination:pagination.value})}
function request({pagination:p}){loading.value=true;Promise.all([proxy.$axios.get('/compras',{params:{...params(),page:p.page,per_page:p.rowsPerPage}}),proxy.$axios.get('/compras-resumen',{params:params()})]).then(([a,b])=>{rows.value=a.data.data;pagination.value={...p,rowsNumber:a.data.total};Object.assign(summary,b.data)}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudieron cargar las compras')).finally(()=>loading.value=false)}
function detail(row){proxy.$axios.get(`/compras/${row.id}`).then(r=>{Object.assign(selected,r.data);dialog.value=true})}
function printRow(row){proxy.$axios.get(`/compras/${row.id}`).then(r=>printPurchase(r.data,company)).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo cargar la compra'))}
function cancel(row){proxy.$alert.dialog(`¿Anular ${row.numero}? Se descontará el stock ingresado.`).onOk(()=>proxy.$axios.put(`/compras/${row.id}/anular`).then(()=>{proxy.$alert.success('Compra anulada');load()}).catch(e=>proxy.$alert.error(e.response?.data?.message||'No se pudo anular')))}
proxy.$axios.get('/configuracion').then(({data})=>Object.assign(company,data,{logo_url:data.logo?`${proxy.$imgBase}/images/${data.logo}`:''}))
load()
</script>
