<template>
  <q-page class="order-page q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-h6">Crear pedido</div><div class="text-caption text-grey-7">Selecciona un cliente desde el mapa o la tabla</div></div><q-space/><q-input v-model="orderDate" outlined dense type="date" label="Pedidos registrados el" style="width:185px" class="q-mr-sm" @update:model-value="loadClients"/><div class="legend"><span class="dot dot--free"/>Sin pedido <span class="dot dot--ordered"/>Con pedido</div><q-btn flat icon="assignment" label="Ver pedidos" no-caps to="/pedidos"/></div>
    <q-card flat bordered><div ref="mapElement" class="order-map"/></q-card>
    <q-card flat bordered class="q-mt-sm"><q-card-section class="row q-col-gutter-sm q-pa-sm"><q-input v-model="search" outlined dense clearable label="Buscar cliente" class="col-12 col-md-5"><template #prepend><q-icon name="search"/></template></q-input></q-card-section>
      <q-table flat dense :rows="filteredClients" :columns="columns" row-key="id" :pagination="{rowsPerPage:10}">
        <template #body="p"><q-tr :props="p" :class="p.row.tiene_pedido?'client-row--ordered':'client-row--free'"><q-td auto-width><q-icon name="location_on" :color="p.row.tiene_pedido?'positive':'primary'" size="22px"/></q-td><q-td><b>{{p.row.nombre}}</b><div class="text-caption">{{p.row.nit?`NIT ${p.row.nit}`:''}}</div></q-td><q-td>{{p.row.direccion}}<div class="text-caption">{{p.row.zona}}</div></q-td><q-td>{{p.row.celular||p.row.telefono}}</q-td><q-td class="text-center"><q-badge :color="p.row.tiene_pedido?'positive':'blue'">{{p.row.tiene_pedido?'PEDIDO REGISTRADO':'SIN PEDIDO'}}</q-badge></q-td><q-td class="text-right"><q-btn color="primary" dense unelevated icon="add_shopping_cart" label="Pedido" no-caps @click="openOrder(p.row)"/></q-td></q-tr></template>
      </q-table>
    </q-card>

    <q-dialog v-model="dialog" persistent><q-card style="width:1050px;max-width:97vw"><q-card-section class="row items-center q-py-sm"><div><div class="text-h6">Nuevo pedido</div><div class="text-caption"><q-icon name="person_pin_circle"/> {{client.nombre}} · {{client.direccion}}</div></div><q-space/><q-btn round flat icon="close" v-close-popup/></q-card-section><q-separator/>
      <div class="row">
        <div class="col-12 col-md-6 q-pa-sm"><q-input v-model="productSearch" outlined dense clearable label="Buscar producto"><template #prepend><q-icon name="search"/></template></q-input><div class="products-grid"><q-card v-for="p in filteredProducts" :key="p.id" flat bordered class="product cursor-pointer" @click="addProduct(p)"><div class="product__image"><img v-if="p.foto" :src="photoUrl(p.foto)"/><q-icon v-else name="inventory_2" size="38px" color="grey-5"/></div><q-card-section class="q-pa-xs"><div class="text-caption text-weight-bold ellipsis-2-lines">{{p.nombre}}</div><div class="text-primary text-weight-bold">Bs {{money(p.precio_venta)}}</div></q-card-section></q-card></div></div>
        <div class="col-12 col-md-6 q-pa-sm bg-grey-1"><div class="text-subtitle2 text-weight-bold q-mb-xs">Productos del pedido</div><q-list v-if="cart.length" bordered separator class="cart-list"><q-item v-for="item in cart" :key="item.producto_id" dense><q-item-section><q-item-label>{{item.nombre}}</q-item-label><div class="row q-col-gutter-xs q-mt-xs"><q-input v-model.number="item.cantidad" outlined dense type="number" min=".001" step=".001" label="Cantidad" class="col-5"/><q-input v-model.number="item.precio_unitario" outlined dense type="number" min="0" step=".0001" label="Precio" prefix="Bs" class="col-5"/><q-btn round flat dense color="negative" icon="delete" @click="removeProduct(item)"/></div></q-item-section><q-item-section side><b>Bs {{money(item.cantidad*item.precio_unitario)}}</b></q-item-section></q-item></q-list><div v-else class="empty-cart"><q-icon name="shopping_cart" size="42px"/><div>Selecciona productos</div></div>
          <div class="row q-col-gutter-xs q-mt-sm"><q-input v-model="order.fecha_entrega" outlined dense type="date" label="Fecha entrega" class="col-6"/><q-select v-model="order.tipo_pago" outlined dense :options="['EFECTIVO','QR','CREDITO']" label="Pago" class="col-6"/><q-input v-model="order.direccion_entrega" outlined dense label="Dirección de entrega" class="col-12 col-sm-8"/><div class="col-12 col-sm-4"><q-btn outline color="primary" icon="edit_location_alt" label="Cambiar ubicación" no-caps class="full-width" @click="deliveryMapDialog=true"/></div><div class="col-12 delivery-coordinates"><q-icon name="my_location"/> Entrega: {{coord(order.latitud_entrega)}}, {{coord(order.longitud_entrega)}}</div><q-input v-model="order.observacion" outlined dense autogrow label="Observación" class="col-12"/></div><div class="row text-h6 text-primary q-mt-sm"><b>Total</b><q-space/><b>Bs {{money(total)}}</b></div>
        </div>
      </div><q-separator/><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="positive" icon="save" label="Registrar pedido" :disable="!cart.length" :loading="saving" @click="saveOrder"/></q-card-actions></q-card></q-dialog>
    <q-dialog v-model="deliveryMapDialog" @show="initDeliveryMap" @hide="destroyDeliveryMap"><q-card style="width:920px;max-width:96vw"><q-card-section class="row items-center q-py-sm"><div><b>Ubicación de entrega</b><div class="text-caption">Haz clic en el punto exacto donde debe entregarse el pedido</div></div><q-space/><q-btn flat round icon="close" v-close-popup/></q-card-section><div ref="deliveryMapElement" class="delivery-map"/><q-card-section class="row items-center q-py-sm"><q-icon name="location_on" color="red" class="q-mr-xs"/><span>{{coord(order.latitud_entrega)}}, {{coord(order.longitud_entrega)}}</span><q-space/><q-btn color="primary" icon="check" label="Usar esta ubicación" v-close-popup/></q-card-section></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, getCurrentInstance, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
const localDate=value=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const tomorrowDate=()=>{const d=new Date();d.setDate(d.getDate()+1);return localDate(d)}
const {proxy}=getCurrentInstance(),mapElement=ref(null),deliveryMapElement=ref(null),clients=ref([]),products=ref([]),search=ref(''),productSearch=ref(''),orderDate=ref(localDate(new Date())),dialog=ref(false),deliveryMapDialog=ref(false),saving=ref(false),client=reactive({}),order=reactive({fecha_entrega:tomorrowDate(),direccion_entrega:'',latitud_entrega:null,longitud_entrega:null,tipo_pago:'EFECTIVO',observacion:''}),cart=ref([])
let map=null,markers=[],deliveryMap=null,deliveryMarker=null
const columns=[{name:'pin',label:'',field:'id'},{name:'cliente',label:'Cliente',field:'nombre',align:'left'},{name:'direccion',label:'Dirección',field:'direccion',align:'left'},{name:'telefono',label:'Contacto',field:'celular',align:'left'},{name:'estado',label:'Estado',field:'tiene_pedido',align:'center'},{name:'actions',label:'',field:'id'}]
const filteredClients=computed(()=>{const q=search.value.toLowerCase();return clients.value.filter(c=>!q||`${c.nombre} ${c.direccion} ${c.nit}`.toLowerCase().includes(q))}),filteredProducts=computed(()=>{const q=productSearch.value.toLowerCase();return products.value.filter(p=>!q||`${p.nombre} ${p.codigo}`.toLowerCase().includes(q))}),total=computed(()=>cart.value.reduce((s,i)=>s+Number(i.cantidad)*Number(i.precio_unitario),0))
const money=v=>Number(v||0).toFixed(2),photoUrl=p=>`${proxy.$imgBase}/images/${p}`,coord=v=>v===null||v===undefined?'Sin coordenada':Number(v).toFixed(6)
function markerIcon(ordered){return L.divIcon({className:'order-marker-wrap',html:`<div class="order-marker ${ordered?'order-marker--done':''}"><span class="material-icons">${ordered?'check':'person'}</span></div>`,iconSize:[34,42],iconAnchor:[17,42]})}
function renderMarkers(){markers.forEach(m=>m.remove());markers=[];const bounds=[];clients.value.forEach(c=>{if(c.latitud===null||c.longitud===null)return;const pos=[Number(c.latitud),Number(c.longitud)],m=L.marker(pos,{icon:markerIcon(c.tiene_pedido)}).addTo(map).bindTooltip(`${c.nombre}${c.tiene_pedido?' · CON PEDIDO':''}`);m.on('click',()=>openOrder(c));markers.push(m);bounds.push(pos)});if(bounds.length)map.fitBounds(bounds,{padding:[35,35],maxZoom:14})}
function loadClients(){return proxy.$axios.get('/pedidos-clientes',{params:{fecha:orderDate.value}}).then(r=>{clients.value=r.data;renderMarkers()})}
function openOrder(c){Object.assign(client,c);Object.assign(order,{fecha_entrega:tomorrowDate(),direccion_entrega:c.direccion||'',latitud_entrega:c.latitud===null?null:Number(c.latitud),longitud_entrega:c.longitud===null?null:Number(c.longitud),tipo_pago:'EFECTIVO',observacion:''});cart.value=[];productSearch.value='';dialog.value=true}
function addProduct(p){const found=cart.value.find(i=>i.producto_id===p.id);if(found)found.cantidad++;else cart.value.push({producto_id:p.id,nombre:p.nombre,cantidad:1,precio_unitario:Number(p.precio_venta)||0})}
function removeProduct(item){cart.value=cart.value.filter(i=>i!==item)}
async function saveOrder(){saving.value=true;try{const {data}=await proxy.$axios.post('/pedidos',{cliente_id:client.id,...order,detalles:cart.value});proxy.$alert.success(`Pedido ${data.numero} registrado`);if(orderDate.value===localDate(new Date())){const row=clients.value.find(c=>c.id===client.id);if(row){row.tiene_pedido=true;row.cantidad_pedidos_fecha=Number(row.cantidad_pedidos_fecha||0)+1}}renderMarkers();dialog.value=false}catch(e){proxy.$alert.error(Object.values(e.response?.data?.errors||{})[0]?.[0]||e.response?.data?.message||'No se pudo registrar el pedido')}finally{saving.value=false}}
function initDeliveryMap(){const center=order.latitud_entrega!==null&&order.longitud_entrega!==null?[Number(order.latitud_entrega),Number(order.longitud_entrega)]:[-17.9647,-67.1060];deliveryMap=L.map(deliveryMapElement.value).setView(center,16);L.tileLayer('https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',{maxZoom:20,attribution:'Google Maps'}).addTo(deliveryMap);deliveryMarker=L.marker(center).addTo(deliveryMap);deliveryMap.on('click',e=>{order.latitud_entrega=Number(e.latlng.lat.toFixed(7));order.longitud_entrega=Number(e.latlng.lng.toFixed(7));deliveryMarker.setLatLng(e.latlng)})}
function destroyDeliveryMap(){deliveryMap?.remove();deliveryMap=null;deliveryMarker=null}
onMounted(()=>{map=L.map(mapElement.value).setView([-17.9647,-67.1060],13);L.tileLayer('https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',{maxZoom:20,attribution:'Google Maps'}).addTo(map);loadClients();proxy.$axios.get('/productos',{params:{per_page:0}}).then(r=>products.value=r.data.data)})
onBeforeUnmount(()=>{map?.remove();destroyDeliveryMap()})
</script>
<style>.order-map{height:43vh;min-height:330px}.delivery-map{height:520px;max-height:68vh}.delivery-coordinates{padding:4px 7px!important;border-radius:5px;color:#546e7a;background:#eaf3fb;font-size:11px}.legend{display:flex;align-items:center;gap:5px;margin-right:12px;font-size:11px}.dot{width:10px;height:10px;border-radius:50%;display:inline-block}.dot--free{background:#1565c0}.dot--ordered{background:#2e7d32}.client-row--ordered{background:#e8f5e9}.client-row--free{background:#f7fbff}.products-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:6px;margin-top:7px;max-height:55vh;overflow:auto}.product{overflow:hidden}.product__image{height:72px;display:flex;align-items:center;justify-content:center;background:#f5f7f8}.product__image img{width:100%;height:100%;object-fit:contain}.cart-list{max-height:30vh;overflow:auto}.empty-cart{text-align:center;color:#90a4ae;padding:28px}.order-marker-wrap{background:transparent;border:0}.order-marker{width:34px;height:34px;display:flex;align-items:center;justify-content:center;border:3px solid #fff;border-radius:50% 50% 50% 0;transform:rotate(-45deg);color:#fff;background:#1565c0;box-shadow:0 3px 8px rgba(0,0,0,.35)}.order-marker--done{background:#2e7d32}.order-marker span{font-size:18px;transform:rotate(45deg)}</style>
