<template>
  <q-page class="q-pa-sm">
    <div class="row items-center q-mb-sm"><div><div class="text-h6">Pedidos</div><div class="text-caption text-grey-7">Seguimiento e historial de pedidos</div></div><q-space/><q-btn flat color="red" icon="map" label="Mapa de pedidos" no-caps class="q-mr-xs" @click="ordersMapDialog=true"/><q-btn-dropdown flat color="primary" icon="download" label="Exportar" no-caps class="q-mr-xs"><q-list dense><q-item clickable v-close-popup @click="download('excel')"><q-item-section avatar><q-icon name="table_view" color="positive"/></q-item-section><q-item-section>Excel</q-item-section></q-item><q-item clickable v-close-popup @click="download('pdf')"><q-item-section avatar><q-icon name="picture_as_pdf" color="negative"/></q-item-section><q-item-section>PDF</q-item-section></q-item></q-list></q-btn-dropdown><q-btn color="primary" icon="add" label="Crear pedido" no-caps to="/pedidos/nuevo"/></div>
    <q-card flat bordered><q-card-section class="row q-col-gutter-sm q-pa-sm"><q-input v-model="search" outlined dense debounce="300" clearable label="Buscar número o cliente" class="col-12 col-md-4" @update:model-value="load"/><q-select v-model="statusFilter" outlined dense clearable :options="statuses" label="Estado" class="col-6 col-md-2" @update:model-value="load"/><q-input v-model="from" outlined dense type="date" label="Entrega desde" class="col-6 col-md-2" @update:model-value="load"/><q-input v-model="to" outlined dense type="date" label="Entrega hasta" class="col-6 col-md-2" @update:model-value="load"/></q-card-section>
      <q-table flat dense :rows="rows" :columns="columns" row-key="id" :loading="loading" v-model:pagination="pagination" @request="request">
        <template #body-cell-fecha="p"><q-td :props="p"><div class="date-box"><q-icon name="schedule" color="blue-grey"/><div><b>{{dateOnly(p.row.fecha)}}</b><small>{{timeOnly(p.row.fecha)}}</small></div></div></q-td></template>
        <template #body-cell-entrega="p"><q-td :props="p"><div class="date-box date-box--delivery"><q-icon name="local_shipping" color="primary"/><div><b>{{dateOnly(p.row.fecha_entrega)}}</b><small>Fecha de entrega</small></div></div></q-td></template>
        <template #body-cell-total="p"><q-td :props="p"><b>Bs {{money(p.value)}}</b></q-td></template>
        <template #body-cell-estado="p"><q-td :props="p"><q-badge :color="statusColor(p.value)">{{p.value}}</q-badge></q-td></template>
        <template #body-cell-actions="p"><q-td :props="p"><q-btn-dropdown dense flat color="primary" icon="more_vert" dropdown-icon="none"><q-list dense style="min-width:180px"><q-item clickable v-close-popup @click="show(p.row)"><q-item-section avatar><q-icon name="visibility"/></q-item-section><q-item-section>Ver detalle</q-item-section></q-item><q-separator/><q-item v-for="s in statuses" :key="s" clickable v-close-popup @click="changeStatus(p.row,s)"><q-item-section avatar><q-icon name="circle" :color="statusColor(s)" size="12px"/></q-item-section><q-item-section>Marcar {{s}}</q-item-section></q-item></q-list></q-btn-dropdown></q-td></template>
      </q-table>
    </q-card>
    <q-dialog v-model="dialog"><q-card style="width:800px;max-width:96vw"><q-card-section class="row items-center"><div><div class="text-h6">{{selected.numero}}</div><div class="text-caption">{{selected.cliente_nombre}} · {{date(selected.fecha)}}</div></div><q-space/><q-btn v-if="hasDeliveryLocation" round flat color="red" icon="location_on" @click="mapDialog=true"><q-tooltip>Ver lugar de entrega</q-tooltip></q-btn><q-badge :color="statusColor(selected.estado)">{{selected.estado}}</q-badge><q-btn round flat icon="close" v-close-popup/></q-card-section><q-separator/><q-table flat dense :rows="selected.detalles||[]" :columns="detailColumns" row-key="id" hide-pagination :rows-per-page-options="[0]"/><q-card-section><div>Entrega: {{selected.fecha_entrega||'Sin fecha'}} · {{selected.direccion_entrega}}</div><div class="text-caption">{{selected.observacion}}</div><div class="text-right text-h6 text-primary">Total Bs {{money(selected.total)}}</div></q-card-section></q-card></q-dialog>
    <q-dialog v-model="mapDialog" @show="initMap" @hide="destroyMap"><q-card style="width:900px;max-width:96vw"><q-card-section class="row items-center q-py-sm"><div><b>Ubicación de entrega — {{selected.numero}}</b><div class="text-caption">{{selected.cliente_nombre}} · {{selected.direccion_entrega}}</div></div><q-space/><q-btn round flat icon="close" v-close-popup/></q-card-section><div ref="mapElement" class="order-detail-map"/></q-card></q-dialog>
    <q-dialog v-model="ordersMapDialog" maximized @show="initOrdersMap" @hide="destroyOrdersMap"><q-card><q-card-section class="orders-map-header"><div><div class="text-h6">Mapa de pedidos</div><div class="text-caption">{{from}} al {{to}} · {{mappedOrders.length}} pedidos con ubicación</div></div><q-space/><div class="map-legend"><span><i class="legend-dot bg-orange"/>Pendiente</span><span><i class="legend-dot bg-blue"/>Preparando</span><span><i class="legend-dot bg-positive"/>Entregado</span><span><i class="legend-dot bg-negative"/>Cancelado</span></div><q-btn round flat icon="close" v-close-popup/></q-card-section><div ref="ordersMapElement" class="orders-map"/></q-card></q-dialog>
  </q-page>
</template>
<script setup>
import { computed, getCurrentInstance, onBeforeUnmount, reactive, ref } from 'vue'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
const localDate=value=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const today=localDate(new Date())
const {proxy}=getCurrentInstance(),rows=ref([]),loading=ref(false),search=ref(''),statusFilter=ref(null),from=ref(today),to=ref(today),dialog=ref(false),mapDialog=ref(false),ordersMapDialog=ref(false),mapElement=ref(null),ordersMapElement=ref(null),selected=reactive({}),pagination=ref({page:1,rowsPerPage:20,rowsNumber:0}),statuses=['PENDIENTE','PREPARANDO','ENTREGADO','CANCELADO']
let deliveryMap=null,ordersMap=null
const hasDeliveryLocation=computed(()=>selected.latitud_entrega!==null&&selected.latitud_entrega!==undefined&&selected.longitud_entrega!==null&&selected.longitud_entrega!==undefined)
const mappedOrders=computed(()=>rows.value.filter(r=>r.latitud_entrega!==null&&r.longitud_entrega!==null))
const columns=[{name:'actions',label:'',field:'id'},{name:'numero',label:'N.º pedido',field:'numero',align:'left'},{name:'fecha',label:'Fecha',field:r=>date(r.fecha),align:'left'},{name:'cliente',label:'Cliente',field:'cliente_nombre',align:'left'},{name:'entrega',label:'Entrega',field:'fecha_entrega',align:'left'},{name:'items',label:'Productos',field:'detalles_count',align:'center'},{name:'total',label:'Total',field:'total',align:'right'},{name:'estado',label:'Estado',field:'estado',align:'center'}]
const detailColumns=[{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Producto',field:'nombre',align:'left'},{name:'cantidad',label:'Cantidad',field:'cantidad',align:'right'},{name:'precio',label:'Precio',field:r=>`Bs ${money(r.precio_unitario)}`,align:'right'},{name:'total',label:'Total',field:r=>`Bs ${money(r.total)}`,align:'right'}]
const money=v=>Number(v||0).toFixed(2),date=v=>{if(!v)return '';const d=new Date(v);return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`},statusColor=s=>({PENDIENTE:'orange',PREPARANDO:'blue',ENTREGADO:'positive',CANCELADO:'negative'}[s]||'grey')
const dateOnly=v=>{if(!v)return 'Sin fecha';const raw=String(v).substring(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){const [y,m,d]=raw.split('-');return `${d}/${m}/${y}`}const d=new Date(v);return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`}
const timeOnly=v=>{if(!v)return '';const d=new Date(v);return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} h`}
const params=()=>({q:search.value,estado:statusFilter.value,desde:from.value,hasta:to.value})
function load(){request({pagination:pagination.value})}function request({pagination:p}){loading.value=true;proxy.$axios.get('/pedidos',{params:{...params(),page:p.page,per_page:p.rowsPerPage}}).then(r=>{rows.value=r.data.data;pagination.value={...p,rowsNumber:r.data.total}}).finally(()=>loading.value=false)}
function show(row){proxy.$axios.get(`/pedidos/${row.id}`).then(r=>{Object.assign(selected,r.data);dialog.value=true})}function changeStatus(row,estado){if(row.estado===estado)return;proxy.$axios.put(`/pedidos/${row.id}/estado`,{estado}).then(()=>{proxy.$alert.success('Estado actualizado');load()})}load()
async function download(type){try{const response=await proxy.$axios.get(`/pedidos-exportar/${type}`,{params:params(),responseType:'blob'});const url=URL.createObjectURL(response.data),a=document.createElement('a');a.href=url;a.download=`pedidos_${from.value}_${to.value}.${type==='excel'?'xlsx':'pdf'}`;a.click();URL.revokeObjectURL(url)}catch{proxy.$alert.error('No se pudo exportar el reporte')}}
function initMap(){const position=[Number(selected.latitud_entrega),Number(selected.longitud_entrega)];deliveryMap=L.map(mapElement.value).setView(position,17);L.tileLayer('https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',{maxZoom:20,attribution:'Google Maps'}).addTo(deliveryMap);L.marker(position).addTo(deliveryMap).bindPopup(`<b>${selected.cliente_nombre}</b><br>${selected.direccion_entrega||''}`).openPopup()}
function destroyMap(){deliveryMap?.remove();deliveryMap=null}
function orderMapIcon(order){const color={PENDIENTE:'#f57c00',PREPARANDO:'#1976d2',ENTREGADO:'#21ba45',CANCELADO:'#c10015'}[order.estado]||'#607d8b';return L.divIcon({className:'order-status-marker-wrap',html:`<div class="order-status-marker" style="background:${color}"><span class="material-icons">${order.estado==='ENTREGADO'?'check':'local_shipping'}</span></div>`,iconSize:[38,46],iconAnchor:[19,46]})}
function initOrdersMap(){ordersMap=L.map(ordersMapElement.value).setView([-17.9647,-67.1060],13);L.tileLayer('https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',{maxZoom:20,attribution:'Google Maps'}).addTo(ordersMap);const bounds=[];mappedOrders.value.forEach(order=>{const pos=[Number(order.latitud_entrega),Number(order.longitud_entrega)];L.marker(pos,{icon:orderMapIcon(order)}).addTo(ordersMap).bindPopup(`<b>${order.numero}</b><br>${order.cliente_nombre}<br><b>${order.estado}</b><br>Entrega: ${dateOnly(order.fecha_entrega)}<br>Bs ${money(order.total)}`);bounds.push(pos)});if(bounds.length)ordersMap.fitBounds(bounds,{padding:[45,45],maxZoom:15})}
function destroyOrdersMap(){ordersMap?.remove();ordersMap=null}onBeforeUnmount(()=>{destroyMap();destroyOrdersMap()})
</script>
<style scoped>.date-box{display:inline-flex;align-items:center;gap:7px;min-width:112px;padding:5px 8px;border:1px solid #dfe7ec;border-radius:8px;background:#f8fafb}.date-box div{display:flex;flex-direction:column;line-height:1.1}.date-box b{font-size:12px}.date-box small{margin-top:3px;color:#78909c;font-size:9px}.date-box--delivery{border-color:#bbdefb;background:#eaf4fd}.order-detail-map{height:520px;max-height:72vh}.orders-map-header{display:flex;align-items:center;gap:12px;height:64px}.orders-map{height:calc(100vh - 64px)}.map-legend{display:flex;gap:13px;font-size:11px}.map-legend span{display:flex;align-items:center;gap:4px}.legend-dot{display:inline-block;width:10px;height:10px;border-radius:50%}:global(.order-status-marker-wrap){background:transparent;border:0}:global(.order-status-marker){width:38px;height:38px;display:flex;align-items:center;justify-content:center;border:3px solid #fff;border-radius:50% 50% 50% 0;transform:rotate(-45deg);color:#fff;box-shadow:0 3px 9px rgba(0,0,0,.35)}:global(.order-status-marker span){font-size:19px;transform:rotate(45deg)}@media(max-width:700px){.map-legend{display:none}}</style>
